version: '3.8'
services:
   flask-app:
    image: bee/mh-quest-log:latest
    build: ./
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
      - DATABASE_URI: ${DATABASE_URI}
      - SECRET_KEY: ${SECRET_KEY}